# Generated by Django 5.2.2 on 2025-06-09 12:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RemindMe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TODOO',
            new_name='REMINDME',
        ),
    ]
